'use client';

import { useT } from '@contentfactory/react/translation/get.transation.service.client';

export const PUBLIC_COPY_KEYS = [
  'navProduct',
  'navPlatforms',
  'navSecurity',
  'navDocs',
  'navDemo',
  'navSections',
  'navLanguage',
  'tryDemo',
  'signUp',
  'homeTitle',
  'homeBody',

  // The six steps of the one process the landing page tells. The same six
  // words label the path inside the hero demo, the strip under it and the
  // scene numbers, because a visitor who meets "Adapt" three times under three
  // names has been shown three products.
  'stageIdea',
  'stageDraft',
  'stageAdapt',
  'stageApprove',
  'stagePublish',
  'stageAnalytics',
  'soon',
  'processLabel',

  // The one sample article every product shot is about. One piece of content
  // followed from idea to result is the page's argument; five unrelated
  // samples would be five screenshots.
  'sampleTitle',
  'sampleLead',
  'sampleBody',

  'heroDemoLabel',
  'statusDraftSaved',
  'heroChannelsLabel',
  'heroMoreIntegrations',

  'ideaTitle',
  'ideaBody',
  'ideaQuery',
  'ideaSearchLanguages',
  'ideaOutputLabel',
  'ideaSourcesLabel',
  'ideaKindReport',
  'ideaKindArticle',
  'ideaKindData',
  'ideaKindPractice',
  'ideaThesisLabel',
  'ideaThesis',

  'draftTitle',
  'draftBody',
  'draftDemoLabel',
  'draftTabText',
  'draftTabMedia',
  'draftTabLinks',
  'draftTabTags',
  'draftMeta',
  'draftAutosave',
  'draftSavedAt',
  'draftHandoff',
  'draftSectionTitle',
  'draftSectionBody',
  'brandVoiceTitle',
  'brandVoiceBody',

  'adaptTitle',
  'adaptBody',
  'adaptNote',
  'adaptTabsLabel',
  'adaptCharLimit',
  'adaptTextFacebook',
  'adaptTextYoutube',
  'adaptTextInstagram',
  'adaptTextTiktok',
  'adaptTextTelegram',
  'adaptSyncNote',
  'adaptReady',

  'approveTitle',
  'approveBody',
  'approveDemoLabel',
  'statusInReview',
  'approveUpdated',
  'commentOneAuthor',
  'commentOneBody',
  'commentTwoAuthor',
  'commentTwoBody',
  'approveApprove',
  'approveReturn',
  'calendarLabel',
  'calendarMonth',
  'calendarWeekdays',
  'calendarSlot',
  'statusScheduled',

  'platformsTitle',
  'platformsBody',
  'platformsNote',

  'analyticsTitle',
  'analyticsBody',
  'analyticsDepthNote',
  'analyticsSubject',
  'demoData',
  'metricViews',
  'metricReach',
  'metricReactions',
  'metricClicks',
  'analyticsChartLabel',
  'analyticsRange',
  'analyticsLoopTitle',
  'analyticsLoopBody',

  'ctaTitle',
  'ctaBody',

  'productTitle',
  'productBody',
  'availableTitle',
  'availableBody',
  'roadmapTitle',
  'roadmapBody',
  'securityTitle',
  'securityBody',
  'tenantIsolationTitle',
  'tenantIsolationBody',
  'encryptedKeysTitle',
  'encryptedKeysBody',
  'backupRecoveryTitle',
  'backupRecoveryBody',
  'deletionExportTitle',
  'deletionExportBody',
  'securityLimitsTitle',
  'securityLimitsBody',
  'docsTitle',
  'docsBody',
  'docsPlanTitle',
  'docsPlanBody',
  'docsReviewTitle',
  'docsReviewBody',
  'docsScheduleTitle',
  'docsScheduleBody',
  'demoTitle',
  'demoBody',
  'plan',
  'planDetail',
  'draft',
  'draftDetail',
  'review',
  'reviewDetail',
  'schedule',
  'scheduleDetail',
  'demoRegion',
  'result',
  'resultDetail',
  'demoPublished',
  'demoChannelsLabel',
  'demoNoChannels',
  'demoNotSent',
  'demoBestChannel',
  'demoApproved',
  'demoOverLimit',
  'demoWithinLimit',
  'demoNothingLeaves',
  'next',
  'reset',
  'emailTitle',
  'emailBody',
  'emailContinue',
  'emailLabel',
  'passwordLabel',
  'workspaceOptional',
  'createAccount',
  'newsletterConsent',
  'legalUnavailable',
  'authOptions',
  'registrationError',
  'signIn',
  'legalNav',
  'legalPrivacy',
  'legalTerms',
  'legalSubprocessors',
  'legalUpdated',
  'legalTranslationPending',
  'legalUnavailableTitle',
  'legalUnavailableBody',
] as const;

export type PublicCopyKey = (typeof PUBLIC_COPY_KEYS)[number];

const translationKey = (key: PublicCopyKey) =>
  `public_saas_${key.replace(
    /[A-Z]/g,
    (letter) => `_${letter.toLowerCase()}`
  )}`;

export function usePublicCopy() {
  const t = useT();
  // `values` carries i18next interpolation, which the legal pages need to name
  // the language a visitor is being shown when their own has no document yet.
  // Callers that pass nothing behave exactly as before.
  return (key: PublicCopyKey, values?: Record<string, string>) =>
    t(translationKey(key), values) as string;
}
