export const channelsCopy = {
  ru: {
    title: 'Каналы',
    subtitle: 'Шаг 2 · куда публикуем и как там пишем',
    connect: 'Подключить канал',
    view: 'Вид списка',
    cards: 'Карточки',
    table: 'Таблица',
    filter: 'Состояние канала',
    all: 'Все',
    working: 'Работают',
    attention: 'Требуют внимания',
    disabled: 'Выключены',
    activeState: 'работает',
    refreshState: 'нужно переподключить',
    disabledState: 'выключен',
    incompleteState: 'подключение не закончено',
    search: 'Найти канал…',
    own: 'Свои каналы',
    connectNew: 'Подключить новый канал',
    connectHint: 'Выберите площадку и подключите канал.',
    writing: 'Как пишем',
    fill: 'Заполнить карточку',
    open: 'Открыть',
    defaults: 'умолчания',
    stored: 'заполнена',
    notStored: 'карточка не заполнена',
    lastPost: 'последний пост',
    posts: 'постов',
    slots: 'слотов в день',
    noSlots: 'без расписания',
    channel: 'Канал',
    state: 'Состояние',
    schedule: 'Расписание',
    latest: 'Последний пост',
    empty: 'Каналов пока нет',
    emptyDescription:
      'Текст пишется под канал: его длину, эмодзи, призыв. Подключите хотя бы один — и заготовки будет куда адаптировать.',
    profileHint:
      'Один канал — одна карточка «Как пишем сюда». Для Telegram доступны рекомендации, для остальных площадок — общие умолчания.',
    readOnly: 'Подключать каналы и менять их настройки может администратор.',
    noMatches: 'Каналы не найдены',
    noMatchesDescription: 'Измените имя или фильтр состояния.',
    clear: 'Сбросить фильтры',
    loading: 'Загружаем каналы',
    error: 'Не удалось загрузить каналы',
    retry: 'Повторить',
    back: '← Все каналы',
    backMobile: '‹ Каналы',
    missing: 'Канал не найден',
    missingDescription: 'Возможно, канал удалён или недоступен в этой области.',
    pieces: 'Заготовки для канала',
    publicLink: 'Открыть на площадке ↗',
    reconnect: 'Переподключить',
    continue: 'Завершить подключение',
    refreshWarning:
      'Доступ к площадке истёк. Переподключите канал, чтобы публикации продолжились.',
    incompleteWarning: 'Подключение канала ещё не закончено.',
    adminHelp: 'Попросите администратора проверить подключение.',
    cardTab: 'Карточка',
    postsTab: 'Выходило',
    connection: 'Подключение',
    edit: 'Изменить',
    timezone: 'Время вашего устройства',
    published: 'опубликован',
    queued: 'запланирован',
    failed: 'ошибка',
    recent: 'Что здесь выходило',
    calendar: 'Все в календаре →',
    noPosts: 'Публикаций пока нет',
    noPostsDescription:
      'Здесь появятся последние публикации и запланированные посты этого канала.',
    postsError: 'Не удалось загрузить публикации',
    untitled: 'Без текста',
    platform: 'Площадка',
    language: 'Язык канала',
    connected: 'Подключён',
    group: 'Группа',
    move: 'переместить',
    changeBot: 'Сменить бота',
    enable: 'Включить',
    disable: 'Выключить',
    remove: 'Удалить',
    chars: 'знаков',
    providerLimit: 'длина по правилам площадки',
  },
  en: {
    title: 'Channels',
    subtitle: 'Step 2 · where we publish and how we write there',
    connect: 'Connect channel',
    view: 'List view',
    cards: 'Cards',
    table: 'Table',
    filter: 'Channel state',
    all: 'All',
    working: 'Working',
    attention: 'Need attention',
    disabled: 'Disabled',
    activeState: 'working',
    refreshState: 'reconnect needed',
    disabledState: 'disabled',
    incompleteState: 'connection incomplete',
    search: 'Find channel…',
    own: 'Your channels',
    connectNew: 'Connect a new channel',
    connectHint: 'Choose a platform and connect a channel.',
    writing: 'How we write',
    fill: 'Set up writing profile',
    open: 'Open',
    defaults: 'defaults',
    stored: 'set up',
    notStored: 'writing profile not set up',
    lastPost: 'last post',
    posts: 'posts',
    slots: 'slots per day',
    noSlots: 'no schedule',
    channel: 'Channel',
    state: 'State',
    schedule: 'Schedule',
    latest: 'Last post',
    empty: 'No channels yet',
    emptyDescription:
      'Writing is shaped for each channel: length, emoji and a call to action. Connect a channel to start adapting your pieces.',
    profileHint:
      'Each channel has its own writing profile. Telegram has recommended settings; other platforms start with general defaults.',
    readOnly:
      'An administrator can connect channels and change their settings.',
    noMatches: 'No matching channels',
    noMatchesDescription: 'Try another name or state filter.',
    clear: 'Clear filters',
    loading: 'Loading channels',
    error: 'Could not load channels',
    retry: 'Retry',
    back: '← All channels',
    backMobile: '‹ Channels',
    missing: 'Channel not found',
    missingDescription:
      'The channel may have been deleted or is unavailable in this workspace.',
    pieces: 'Pieces for channel',
    publicLink: 'Open on platform ↗',
    reconnect: 'Reconnect',
    continue: 'Complete connection',
    refreshWarning:
      'Platform access has expired. Reconnect the channel to resume publishing.',
    incompleteWarning: 'The channel connection is not complete yet.',
    adminHelp: 'Ask an administrator to check the connection.',
    cardTab: 'Profile',
    postsTab: 'Posts',
    connection: 'Connection',
    edit: 'Edit',
    timezone: 'Your device time',
    published: 'published',
    queued: 'scheduled',
    failed: 'error',
    recent: 'What was posted here',
    calendar: 'All in calendar →',
    noPosts: 'No posts yet',
    noPostsDescription:
      'Recent and scheduled posts for this channel will appear here.',
    postsError: 'Could not load posts',
    untitled: 'No text',
    platform: 'Platform',
    language: 'Channel language',
    connected: 'Connected',
    group: 'Group',
    move: 'move',
    changeBot: 'Change bot',
    enable: 'Enable',
    disable: 'Disable',
    remove: 'Delete',
    chars: 'characters',
    providerLimit: 'platform length rules',
  },
} as const;
export type ChannelsLocale = keyof typeof channelsCopy;
