const englishCategories = [
  'Educational',
  'Inspirational',
  'Promotional',
  'Entertaining',
  'Interactive',
  'Behind The Scenes',
  'Testimonial',
  'Informative',
  'Humorous',
  'Seasonal',
  'News',
  'Challenge',
  'Contest',
  'Tips',
  'Tutorial',
  'Poll',
  'Survey',
  'Quote',
  'Event',
  'FAQ',
  'Story',
  'Meme',
  'Review',
  'Announcement',
  'Highlight',
  'Celebration',
  'Reminder',
  'Debate',
  'Update',
  'Trend',
];

const russianCategories = [
  'Образовательный',
  'Вдохновляющий',
  'Рекламный',
  'Развлекательный',
  'Интерактивный',
  'За кулисами',
  'Отзыв',
  'Информационный',
  'Юмористический',
  'Сезонный',
  'Новости',
  'Челлендж',
  'Конкурс',
  'Советы',
  'Руководство',
  'Опрос',
  'Исследование',
  'Цитата',
  'Событие',
  'Частые вопросы',
  'История',
  'Мем',
  'Обзор',
  'Объявление',
  'Главное',
  'Празднование',
  'Напоминание',
  'Дискуссия',
  'Обновление',
  'Тренд',
];

export const agentCategoriesByLanguage = {
  en: englishCategories,
  ru: russianCategories,
} as const;

/** Bilingual compatibility list for classification of already-written posts. */
export const agentCategories = [...englishCategories, ...russianCategories];
