export const calendarPlanningCopy = {
  ru: {
    title: 'Что публикуем',
    schedule: '+ Запланировать',
    allChannels: 'Все каналы',
    channelsLink: 'Все каналы →',
    noDate: 'Дата не выбрана',
    changeDate: 'выбор даты можно поменять в окне поста',
    search: 'Поиск по заголовку и каналу',
    ready: 'Готово и не в плане',
    readyAt: 'готово',
    blank: 'Чистый лист',
    blankHint: 'пост без конвейера',
    cancel: 'Отмена',
    open: 'Открыть в окне поста',
    empty: 'Готовых адаптаций пока нет',
    emptyHint:
      'Тексты под каналы рождаются в разделе «Контент»: мысль → заготовка → адаптация. Готовая адаптация появится здесь, пока она не поставлена в план.',
    content: 'В контент →',
    noMatches: 'Ничего не найдено',
    reset: 'Сбросить поиск и фильтр',
    loading: 'Загружаем адаптации',
    error: 'Не удалось загрузить адаптации',
    retry: 'Повторить',
    openError: 'Не удалось открыть пост. Обновите список и попробуйте ещё раз.',
    readonly: 'Планирование доступно редактору рабочего пространства.',
    noChannels: 'Для поста нужен канал. Подключите его в разделе «Каналы».',
    origin: 'из заготовки',
    originOpen: 'открыть',
  },
  en: {
    title: 'What are we publishing?',
    schedule: '+ Schedule',
    allChannels: 'All channels',
    channelsLink: 'All channels →',
    noDate: 'Date not selected',
    changeDate: 'you can change the date in the post editor',
    search: 'Search by title or channel',
    ready: 'Ready and not scheduled',
    readyAt: 'ready',
    blank: 'Blank page',
    blankHint: 'post without the conveyor',
    cancel: 'Cancel',
    open: 'Open in post editor',
    empty: 'No ready adaptations yet',
    emptyHint:
      'Channel texts start in Content: idea → piece → adaptation. A ready adaptation appears here until it is scheduled.',
    content: 'Go to Content →',
    noMatches: 'No matches',
    reset: 'Clear search and filter',
    loading: 'Loading adaptations',
    error: 'Could not load adaptations',
    retry: 'Try again',
    openError: 'Could not open the post. Refresh the list and try again.',
    readonly: 'Planning is available to workspace editors.',
    noChannels: 'A post needs a channel. Connect one in Channels.',
    origin: 'from piece',
    originOpen: 'open',
  },
} as const;
